doctrine:
    dbal:
        dbname: '%env(string:DB_NAME)%'
        host: '%env(string:DB_HOST)%'
        port: '%env(int:DB_PORT)%'
        user: '%env(string:DB_USER)%'
        password: '%env(string:DB_PASSWORD)%'
        server_version: '%env(string:DB_VERSION)%'
        driver: '%env(string:DB_DRIVER)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
