twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'App/_partials/_form/_post_tags.html.twig'
        - 'App/_partials/_form/_input.html.twig'
        - 'App/_partials/_form/_file.html.twig'

when@test:
    twig:
        strict_variables: true
