when@dev: &dev
    zenstruck_foundry:
        instantiator:
            use_constructor: true
        orm:
            auto_persist: true
            reset:
                connections: [ default ]
                entity_managers: [ default ]
                mode: migrate

when@test: *dev
