files:
    - source: /translations/en/messages+intl-icu.en.xlf
      translation: /translations/%two_letters_code%/messages+intl-icu.%two_letters_code%.%file_extension%
    - source: /translations/en/validators+intl-icu.en.xlf
      translation: /translations/%two_letters_code%/validators+intl-icu.%two_letters_code%.%file_extension%