FROM ubuntu:noble

ARG DEBIAN_FRONTEND=noninteractive

# Environment variables
ENV APP_ENV='prod'
ENV PUID='1001'
ENV PGID='1001'
ENV USER='mendako'

COPY ./docker/entrypoint-dev.sh /entrypoint.sh

# Install some basics dependencies
RUN apt-get update && \
    apt-get install -y curl wget lsb-release software-properties-common gnupg2 && \
# Add User and Group
    addgroup --gid "$PGID" "$USER" && \
    adduser --gecos '' --no-create-home --disabled-password --uid "$PUID" --gid "$PGID" "$USER" && \
# PHP
    add-apt-repository ppa:ondrej/php && \
# Nodejs
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=21 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
# Install packages
    apt-get update && \
    apt-get install -y \
    ca-certificates \
    apt-transport-https \
    libpuzzle-dev \
    gnupg2 \
    git \
    unzip \
    nginx-light \
    openssl \
    ffmpeg \
    php8.5 \
    php8.5-dev \
    php8.5-pgsql \
    php8.5-mysql \
    php8.5-mbstring \
    php8.5-gd \
    php8.5-xml \
    php8.5-zip \
    php8.5-fpm \
    php8.5-intl \
    nodejs && \
    corepack enable && \
#Install composer dependencies
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
# Set permissions \
    chmod +x /entrypoint.sh && \
# Build libpuzzle extension
    cd /tmp && \
    wget https://github.com/benjaminjonard/libpuzzle-php-extension-builder/archive/refs/heads/main.zip && \
    unzip main.zip && \
    cd libpuzzle-php-extension-builder-main/src && \
    phpize && \
    ./configure && \
    make clean && \
    make && \
    make install && \
    echo "extension=libpuzzle.so" >> /etc/php/8.5/fpm/php.ini && \
    echo "extension=libpuzzle.so" >> /etc/php/8.5/cli/php.ini && \
    rm -rf /tmp/libpuzzle-php-extension-builder-main && \
    apt remove php8.5-dev -y

# Add nginx and PHP config files
COPY ./docker/default.conf /etc/nginx/nginx.conf

EXPOSE 80

WORKDIR /var/www/mendako

VOLUME /uploads
VOLUME /thumbnails

HEALTHCHECK CMD curl --fail http://localhost:80/ || exit 1

ENTRYPOINT ["sh", "/entrypoint.sh" ]

CMD [ "nginx" ]
