FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

# Environment variables
ENV APP_ENV='prod'
ENV PUID='1000'
ENV PGID='1000'
ENV USER='mendako'

COPY ./docker/entrypoint-dev.sh /entrypoint.sh

# Add User and Group
RUN addgroup --gid "$PGID" "$USER" && \
    adduser --gecos '' --no-create-home --disabled-password --uid "$PUID" --gid "$PGID" "$USER" && \
# Install some basics dependencies
    apt-get update && \
    apt-get install -y curl wget lsb-release software-properties-common gnupg2 && \
# PHP
    add-apt-repository ppa:ondrej/php && \
# Nodejs
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=21 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
# Install packages
    apt-get update && \
    apt-get install -y \
    ca-certificates \
    apt-transport-https \
    libpuzzle-dev \
    gnupg2 \
    git \
    unzip \
    nginx-light \
    openssl \
    ffmpeg \
    php8.3 \
    php8.3-dev \
    php8.3-pgsql \
    php8.3-mysql \
    php8.3-mbstring \
    php8.3-gd \
    php8.3-xml \
    php8.3-zip \
    php8.3-fpm \
    php8.3-intl \
    nodejs && \
    corepack enable && \
#Install composer dependencies
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
# Set permissions \
    chmod +x /entrypoint.sh && \
    mkdir /run/php && \
# Build libpuzzle extension
    cd /tmp && \
    wget https://github.com/benjaminjonard/libpuzzle-php-extension-builder/archive/refs/heads/main.zip && \
    unzip main.zip && \
    cd libpuzzle-php-extension-builder-main/src && \
    phpize && \
    ./configure && \
    make clean && \
    make && \
    make install && \
    echo "extension=libpuzzle.so" >> /etc/php/8.3/fpm/php.ini && \
    echo "extension=libpuzzle.so" >> /etc/php/8.3/cli/php.ini && \
    rm -rf /tmp/libpuzzle-php-extension-builder-main && \
    apt remove php8.3-dev -y

# Add nginx and PHP config files
COPY ./docker/default.conf /etc/nginx/nginx.conf

EXPOSE 80

WORKDIR /var/www/mendako

VOLUME /uploads
VOLUME /thumbnails

HEALTHCHECK CMD curl --fail http://localhost:80/ || exit 1

ENTRYPOINT ["sh", "/entrypoint.sh" ]

CMD [ "nginx" ]
