[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:frankenphp]
command=frankenphp run --config /etc/caddy/Caddyfile
autostart=true
autorestart=true
stopsignal=SIGTERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:messenger-interactive]
command=php -d memory_limit=%(ENV_WORKER_PHP_MEMORY_LIMIT)s /app/public/bin/console messenger:consume autotag_interactive --time-limit=3600 --memory-limit=%(ENV_WORKER_PHP_MEMORY_LIMIT)s
autostart=true
autorestart=true
stopsignal=SIGTERM
stopwaitsecs=120
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:messenger-batch]
command=php -d memory_limit=%(ENV_WORKER_PHP_MEMORY_LIMIT)s /app/public/bin/console messenger:consume autotag_batch --time-limit=3600 --memory-limit=%(ENV_WORKER_PHP_MEMORY_LIMIT)s
autostart=true
autorestart=true
stopsignal=SIGTERM
stopwaitsecs=120
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
